import { Link, useNavigate } from 'react-router-dom'
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { useCartStore } from '@/stores/cartStore'
import PublicNavbar from '@/components/shared/PublicNavbar'
import PublicFooter from '@/components/shared/PublicFooter'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

export default function CartPage(){const navigate=useNavigate();const {items,updateQuantity,removeItem}=useCartStore();const subtotal=items.reduce((s,x)=>s+Number(x.medicine.price)*x.quantity,0);return <div className="min-h-screen bg-muted/20"><PublicNavbar/><main className="content-shell pb-20 pt-24"><div className="rounded-3xl border border-border/70 bg-card px-6 py-8 shadow-sm sm:px-9"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Order review</span><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Your medicine request</h1><p className="mt-3 max-w-2xl text-muted-foreground">Check each medicine, quantity, pack size, and selling unit before continuing to secure checkout.</p></div>
  {!items.length?<Card className="mt-8 rounded-3xl"><CardContent className="flex flex-col items-center p-14 text-center"><ShoppingBag className="h-12 w-12 text-muted-foreground"/><h2 className="mt-4 text-xl font-semibold">Your cart is empty</h2><Button asChild className="mt-5"><Link to="/medicines">Shop medicines</Link></Button></CardContent></Card>:<div className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{items.map(({medicine,quantity})=><Card key={medicine.id} className="rounded-2xl border-border/70 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><Link to={`/medicines/${medicine.id}`} className="font-semibold hover:text-primary">{medicine.name}</Link><p className="mt-1 text-sm text-muted-foreground">{medicine.strength} · {medicine.dosageForm} · {medicine.packSize||medicine.sellingUnit}</p><p className="mt-2 text-sm font-medium">RWF {Number(medicine.price).toLocaleString()} per {medicine.sellingUnit}</p></div><div className="flex items-center gap-2"><button onClick={()=>updateQuantity(medicine.id,quantity-1)} className="rounded-lg border p-2 transition hover:bg-muted"><Minus className="h-4 w-4"/></button><span className="w-8 text-center font-medium">{quantity}</span><button onClick={()=>updateQuantity(medicine.id,quantity+1)} className="rounded-lg border p-2 transition hover:bg-muted"><Plus className="h-4 w-4"/></button><button aria-label="Remove" onClick={()=>removeItem(medicine.id)} className="ml-2 rounded-lg p-2 text-destructive transition hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div></CardContent></Card>)}</div><Card className="h-fit rounded-3xl border-border/70 shadow-sm lg:sticky lg:top-24"><CardContent className="p-6"><h2 className="text-lg font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><span>RWF {subtotal.toLocaleString()}</span></div><div className="mt-5 flex justify-between border-t pt-5 text-lg font-bold"><span>Total before delivery</span><span>RWF {subtotal.toLocaleString()}</span></div><Button className="mt-6 h-12 w-full rounded-xl" onClick={()=>navigate('/checkout')}>Continue securely</Button><p className="mt-3 text-xs leading-5 text-muted-foreground">Prescription medicines remain requests until a pharmacist reviews and approves them.</p></CardContent></Card></div>}
  </main><PublicFooter/></div>}
