import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { ShieldCheck, Upload } from 'lucide-react'
import api from '@/lib/api'
import { useCartStore } from '@/stores/cartStore'
import PublicNavbar from '@/components/shared/PublicNavbar'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { usePrescriptionDraftStore } from '@/stores/prescriptionDraftStore'

export default function CheckoutPage(){const navigate=useNavigate();const {items,clear}=useCartStore();const draftFiles=usePrescriptionDraftStore(state=>state.files);const clearDraft=usePrescriptionDraftStore(state=>state.clearDraft);const [step,setStep]=useState(localStorage.getItem('guestAccessToken')?'details':'phone');const [busy,setBusy]=useState(false);const [devCode,setDevCode]=useState('');const [form,setForm]=useState({phone:'',code:'',fullName:'',email:'',fulfilmentMethod:'PICKUP',deliveryAddress:'',notificationChannel:'SMS',paymentMethod:'PAY_ON_PICKUP',consent:false});const [files,setFiles]=useState(draftFiles);const rx=items.some(x=>x.medicine.classification==='PRESCRIPTION_REQUIRED'||x.medicine.requiresPrescription)
  const change=e=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});const request=async()=>{setBusy(true);try{const r=await api.post('/orders/otp/request',{phone:form.phone});setDevCode(r.data.data.delivery?.code||'');setStep('otp');toast.success('Verification code requested')}catch(e){toast.error(e.response?.data?.error||e.response?.data?.message||'Could not request code')}finally{setBusy(false)}};const verify=async()=>{setBusy(true);try{const r=await api.post('/orders/otp/verify',{phone:form.phone,code:form.code,fullName:form.fullName||undefined,email:form.email||undefined});localStorage.setItem('guestAccessToken',r.data.data.token);setStep('details');toast.success('Phone verified')}catch(e){toast.error(e.response?.data?.error||'Verification failed')}finally{setBusy(false)}}
  const submit=async()=>{if(!items.length)return;setBusy(true);try{const key=crypto.randomUUID();const response=await api.post('/orders',{items:items.map(x=>({medicineId:x.medicine.id,quantity:x.quantity})),fullName:form.fullName,email:form.email,fulfilmentMethod:form.fulfilmentMethod,deliveryAddress:form.deliveryAddress,notificationChannel:form.notificationChannel,paymentMethod:form.paymentMethod,consent:form.consent},{headers:{'Idempotency-Key':key}});const order=response.data.data;if(rx){if(!files.length){toast.error('Upload the prescription before submitting');setBusy(false);return}const fd=new FormData();files.forEach(file=>fd.append('files',file));await api.post(`/orders/${order.id}/prescription`,fd)}clear();clearDraft();navigate(`/orders/${order.id}`)}catch(e){toast.error(e.response?.data?.error||e.response?.data?.message||'Order could not be submitted')}finally{setBusy(false)}}
  if(!items.length)return <div className="min-h-screen bg-background"><PublicNavbar/><main className="content-shell pt-28"><Card><CardContent className="p-12 text-center">Your cart is empty.</CardContent></Card></main></div>
  const steps=[['phone','Verify'],['otp','Code'],['details','Details']];const activeIndex=steps.findIndex(([key])=>key===step);return <div className="min-h-screen bg-muted/20"><PublicNavbar/><main className="mx-auto max-w-3xl px-4 pb-20 pt-24 sm:px-6"><div className="mb-8 text-center"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Protected patient checkout</span><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Complete your medicine request</h1><p className="mx-auto mt-3 max-w-xl text-muted-foreground">Your phone verification protects the order and any prescription information attached to it.</p></div><div className="mx-auto mb-6 flex max-w-md items-center">{steps.map(([key,label],index)=><div key={key} className="flex flex-1 items-center last:flex-none"><div className="flex flex-col items-center gap-1.5"><span className={`grid h-8 w-8 place-items-center rounded-full border text-xs font-bold transition ${index<=activeIndex?'border-primary bg-primary text-primary-foreground':'bg-background text-muted-foreground'}`}>{index+1}</span><span className="text-[11px] font-medium text-muted-foreground">{label}</span></div>{index<steps.length-1&&<span className={`mx-2 mb-5 h-px flex-1 ${index<activeIndex?'bg-primary':'bg-border'}`}/>}</div>)}</div><Card className="overflow-hidden rounded-3xl border-border/70 shadow-[0_24px_70px_-45px_rgb(0,0,0,0.45)]"><div className="border-b bg-card px-6 py-5 sm:px-8"><p className="font-semibold">{step==='phone'?'Verify your phone':step==='otp'?'Enter verification code':'Delivery and order details'}</p><p className="mt-1 text-sm text-muted-foreground">{step==='details'?`${items.length} medicine item${items.length===1?'':'s'} in this request`:'This takes less than a minute.'}</p></div><CardContent className="p-6 sm:p-8">
    {step==='phone'&&<div className="space-y-5"><div><Label htmlFor="phone">Phone number</Label><Input id="phone" name="phone" value={form.phone} onChange={change} placeholder="+250 7XX XXX XXX" className="mt-2"/></div><Button disabled={busy||!form.phone} onClick={request} className="w-full">Send verification code</Button></div>}
    {step==='otp'&&<div className="space-y-5"><div><Label htmlFor="code">Six-digit code</Label><Input id="code" name="code" inputMode="numeric" maxLength={6} value={form.code} onChange={change} className="mt-2"/>{devCode&&<p className="mt-2 rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-xs">Development provider only: code {devCode}. No SMS was sent.</p>}</div><Button disabled={busy||form.code.length!==6} onClick={verify} className="w-full">Verify phone</Button></div>}
    {step==='details'&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="fullName">Full name</Label><Input id="fullName" name="fullName" value={form.fullName} onChange={change} className="mt-2"/></div><div><Label htmlFor="email">Email (optional)</Label><Input id="email" name="email" type="email" value={form.email} onChange={change} className="mt-2"/></div></div><div><Label>Fulfilment</Label><Select value={form.fulfilmentMethod} onValueChange={v=>setForm({...form,fulfilmentMethod:v})}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="PICKUP">Pickup</SelectItem><SelectItem value="DELIVERY">Delivery</SelectItem></SelectContent></Select></div>{form.fulfilmentMethod==='DELIVERY'&&<div><Label htmlFor="deliveryAddress">Delivery address</Label><Input id="deliveryAddress" name="deliveryAddress" value={form.deliveryAddress} onChange={change} className="mt-2"/></div>}
      {rx&&<div><Label htmlFor="prescription">Prescription files</Label><label htmlFor="prescription" className="mt-2 flex cursor-pointer flex-col items-center rounded-xl border border-dashed p-7 text-center"><Upload className="h-7 w-7 text-primary"/><span className="mt-2 text-sm font-medium">Images, PDF, DOC, DOCX, or ODT — up to 10 MB each</span><span className="mt-1 text-xs text-muted-foreground">Maximum 3 files. A pharmacist must review these before payment.</span></label><input id="prescription" className="sr-only" type="file" multiple accept="image/*,.pdf,.doc,.docx,.odt" onChange={e=>setFiles([...e.target.files])}/>{files.length>0&&<p className="mt-2 text-sm">{files.length} file(s) selected</p>}</div>}
      <label className="flex items-start gap-3 rounded-xl border p-4"><input type="checkbox" name="consent" checked={form.consent} onChange={change} className="mt-1"/><span className="text-sm">I consent to privacy terms and pharmacy processing for this order.</span></label><Button disabled={busy||!form.fullName||!form.consent||(form.fulfilmentMethod==='DELIVERY'&&!form.deliveryAddress)||(rx&&!files.length)} onClick={submit} className="w-full">{rx?'Submit medicine request':'Place OTC order'}</Button><p className="flex gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0"/>Prescription orders cannot proceed to payment or preparation until reviewed and approved by a pharmacist.</p></div>}
  </CardContent></Card></main></div>}
