import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { useParams,Link } from 'react-router-dom'
import { toast } from 'sonner'
import { CheckCircle2,Clock,MessageSquare,Printer } from 'lucide-react'
import api from '@/lib/api'
import PublicNavbar from '@/components/shared/PublicNavbar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card,CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'

const human=s=>s?.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())
function directions(i){const times=(i.administration_times||[]).join(' and ');return `Take ${i.quantity_per_dose} ${i.dose_unit} by ${i.route}${times?` at ${times}`:''}${i.duration_value?` for ${i.duration_value} ${i.duration_unit?.toLowerCase()}`:''}${i.food_relationship?`, ${i.food_relationship.toLowerCase()}`:''}.`}
export default function OrderTrackingPage(){const {id}=useParams();const qc=useQueryClient();const q=useQuery({queryKey:['order',id],queryFn:()=>api.get(`/orders/${id}`).then(r=>r.data.data)});const confirm=useMutation({mutationFn:()=>api.post(`/orders/${id}/confirm`),onSuccess:()=>{toast.success('Approved order confirmed');qc.invalidateQueries({queryKey:['order',id]})},onError:e=>toast.error(e.response?.data?.error||'Could not confirm')});if(q.isLoading)return <div className="min-h-screen bg-muted/20"><PublicNavbar/><main className="content-shell pt-28"><Skeleton className="h-96 rounded-3xl"/></main></div>;if(q.isError)return <div className="min-h-screen bg-muted/20"><PublicNavbar/><main className="content-shell pt-28"><Card><CardContent className="p-12 text-center">Order could not be loaded. Sign in to the account that placed this order to view it securely.</CardContent></Card></main></div>;const o=q.data;return <div className="min-h-screen bg-muted/20"><PublicNavbar/><main className="content-shell pb-20 pt-24"><div className="flex flex-wrap items-start justify-between gap-4 rounded-3xl border border-border/70 bg-card px-6 py-7 shadow-sm sm:px-8"><div><p className="text-sm font-medium text-primary">Order {o.public_reference}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Order tracking</h1></div><Badge className="px-3 py-1.5">{human(o.status)}</Badge></div>
  <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Card><CardContent className="p-6"><h2 className="font-semibold">Medicines</h2><div className="mt-4 divide-y">{o.items.map(x=><div key={x.id} className="flex justify-between gap-4 py-4"><div><p className="font-medium">{x.medicine_snapshot.name}</p><p className="text-sm text-muted-foreground">{x.medicine_snapshot.strength} · {x.selling_unit} · Qty {x.approved_quantity||x.requested_quantity}</p></div><p className="font-medium">RWF {Number(x.total).toLocaleString()}</p></div>)}</div></CardContent></Card>
    {o.instructions?.length>0&&<Card><CardContent className="p-6"><div className="flex justify-between"><h2 className="font-semibold">Pharmacist-verified instructions</h2><Button variant="outline" size="sm" asChild><Link to={`/orders/${o.id}/label`}><Printer className="mr-2 h-4 w-4"/>Print label</Link></Button></div><div className="mt-4 space-y-4">{o.instructions.map(i=><div key={i.id} className="rounded-xl border p-5"><h3 className="font-semibold">{i.medicine_snapshot.name} {i.strength}</h3><p className="mt-3 text-lg leading-7">{directions(i)}</p>{i.special_instructions&&<p className="mt-3 text-sm"><b>Special instructions:</b> {i.special_instructions}</p>}{i.warnings&&<p className="mt-2 text-sm text-amber-600"><b>Warning:</b> {i.warnings}</p>}<p className="mt-3 text-xs text-muted-foreground">Verified {new Date(i.verified_at).toLocaleString()} · Version {i.version}</p></div>)}</div></CardContent></Card>}
  </div><div className="space-y-5"><Card><CardContent className="p-6"><h2 className="font-semibold">Summary</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Subtotal</dt><dd>RWF {Number(o.subtotal).toLocaleString()}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Delivery</dt><dd>RWF {Number(o.delivery_fee).toLocaleString()}</dd></div><div className="flex justify-between border-t pt-3 font-bold"><dt>Total</dt><dd>RWF {Number(o.total).toLocaleString()}</dd></div></dl>{o.status==='APPROVED_AWAITING_PATIENT_CONFIRMATION'&&<Button className="mt-5 w-full" onClick={()=>confirm.mutate()} disabled={confirm.isPending}>Accept approved order</Button>}{o.status==='APPROVED_AWAITING_PAYMENT'&&<Button className="mt-5 w-full" asChild><Link to={`/orders/${o.id}/payment`}>Continue to payment</Link></Button>}{o.status==='PAYMENT_DEFERRED'&&<div className="mt-5 rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm"><b>Pay on pickup confirmed</b><p className="mt-1 text-muted-foreground">RWF {Number(o.total).toLocaleString()} remains due when you collect the order.</p></div>}</CardContent></Card><Button variant="outline" className="w-full" asChild><Link to="/contact"><MessageSquare className="mr-2 h-4 w-4"/>Ask the pharmacy</Link></Button></div></div>
  <div className="mt-8 rounded-2xl border p-5"><h2 className="font-semibold">Status history</h2><div className="mt-4 space-y-3">{o.history.map(h=><div key={h.id} className="flex gap-3 text-sm"><div className="mt-0.5">{h.new_status==='COMPLETED'?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:<Clock className="h-4 w-4 text-primary"/>}</div><div><p className="font-medium">{human(h.new_status)}</p><p className="text-xs text-muted-foreground">{new Date(h.created_at).toLocaleString()}{h.reason?` · ${h.reason}`:''}</p></div></div>)}</div></div>
  </main></div>}
