export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  AUDITOR: 'AUDITOR',
  PATIENT: 'PATIENT',
  GUEST: 'GUEST',
});

export const ORDER_STATUS = Object.freeze({
  CART: 'CART',
  AWAITING_PATIENT_VERIFICATION: 'AWAITING_PATIENT_VERIFICATION',
  AWAITING_PRESCRIPTION: 'AWAITING_PRESCRIPTION',
  SUBMITTED_FOR_REVIEW: 'SUBMITTED_FOR_REVIEW',
  UNDER_PHARMACIST_REVIEW: 'UNDER_PHARMACIST_REVIEW',
  CLARIFICATION_REQUIRED: 'CLARIFICATION_REQUIRED',
  PRESCRIBER_CLARIFICATION_REQUIRED: 'PRESCRIBER_CLARIFICATION_REQUIRED',
  APPROVED_AWAITING_PATIENT_CONFIRMATION: 'APPROVED_AWAITING_PATIENT_CONFIRMATION',
  APPROVED_AWAITING_PAYMENT: 'APPROVED_AWAITING_PAYMENT',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_DEFERRED: 'PAYMENT_DEFERRED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  COMPLETED: 'COMPLETED',
  REJECTED_BY_PHARMACIST: 'REJECTED_BY_PHARMACIST',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
});

export const PRESCRIPTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
});

export const CONVERSATION_STATUS = Object.freeze({
  OPEN: 'OPEN',
  WAITING_PHARMACIST: 'WAITING_PHARMACIST',
  WAITING_PATIENT: 'WAITING_PATIENT',
  ESCALATED: 'ESCALATED',
  CLOSED: 'CLOSED',
});

export const CONVERSATION_PRIORITY = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const CONVERSATION_CONTEXT = Object.freeze({
  PRESCRIPTION: 'PRESCRIPTION',
  MEDICINE: 'MEDICINE',
  GENERAL: 'GENERAL',
});

export const AUDIT_ACTION = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});

export const AUDIT_ENTITY = Object.freeze({
  USER: 'USER',
  PRESCRIPTION: 'PRESCRIPTION',
  ROLE: 'ROLE',
  CONVERSATION: 'CONVERSATION',
  MESSAGE: 'MESSAGE',
  MEDICINE: 'MEDICINE',
  SALE: 'SALE',
  INVENTORY: 'INVENTORY',
  SUPPLIER: 'SUPPLIER',
  STOCK_BATCH: 'STOCK_BATCH',
  CATEGORY: 'CATEGORY',
  SETTINGS: 'SETTINGS',
});

export const ROLE_HIERARCHY = Object.freeze({
  [ROLES.ADMIN]: 10,
  [ROLES.MANAGER]: 8,
  [ROLES.PHARMACIST]: 7,
  [ROLES.INVENTORY_MANAGER]: 6,
  [ROLES.CASHIER]: 5,
  [ROLES.AUDITOR]: 1,
  [ROLES.PATIENT]: 0,
});

export const NOTIFICATION_TYPES = Object.freeze({
  PRESCRIPTION_SUBMITTED: 'PRESCRIPTION_SUBMITTED',
  PRESCRIPTION_UNDER_REVIEW: 'PRESCRIPTION_UNDER_REVIEW',
  PRESCRIPTION_APPROVED: 'PRESCRIPTION_APPROVED',
  PRESCRIPTION_REJECTED: 'PRESCRIPTION_REJECTED',
  PRESCRIPTION_COMPLETED: 'PRESCRIPTION_COMPLETED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  PHARMACIST_RESPONSE: 'PHARMACIST_RESPONSE',
});
