export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  AUDITOR: 'AUDITOR',
  PATIENT: 'PATIENT',
  GUEST: 'GUEST',
});

export const ORDER_STATUS = Object.freeze({
  CART: 'CART',
  AWAITING_PATIENT_VERIFICATION: 'AWAITING_PATIENT_VERIFICATION',
  AWAITING_PRESCRIPTION: 'AWAITING_PRESCRIPTION',
  SUBMITTED_FOR_REVIEW: 'SUBMITTED_FOR_REVIEW',
  UNDER_PHARMACIST_REVIEW: 'UNDER_PHARMACIST_REVIEW',
  CLARIFICATION_REQUIRED: 'CLARIFICATION_REQUIRED',
  PRESCRIBER_CLARIFICATION_REQUIRED: 'PRESCRIBER_CLARIFICATION_REQUIRED',
  APPROVED_AWAITING_PATIENT_CONFIRMATION: 'APPROVED_AWAITING_PATIENT_CONFIRMATION',
  APPROVED_AWAITING_PAYMENT: 'APPROVED_AWAITING_PAYMENT',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_DEFERRED: 'PAYMENT_DEFERRED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  COMPLETED: 'COMPLETED',
  REJECTED_BY_PHARMACIST: 'REJECTED_BY_PHARMACIST',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
});

export const PRESCRIPTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
});

export const CONVERSATION_STATUS = Object.freeze({
  OPEN: 'OPEN',
  WAITING_PHARMACIST: 'WAITING_PHARMACIST',
  WAITING_PATIENT: 'WAITING_PATIENT',
  ESCALATED: 'ESCALATED',
  CLOSED: 'CLOSED',
});

export const CONVERSATION_PRIORITY = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const CONVERSATION_CONTEXT = Object.freeze({
  PRESCRIPTION: 'PRESCRIPTION',
  MEDICINE: 'MEDICINE',
  GENERAL: 'GENERAL',
});

export const AUDIT_ACTION = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});

export const AUDIT_ENTITY = Object.freeze({
  USER: 'USER',
  PRESCRIPTION: 'PRESCRIPTION',
  ROLE: 'ROLE',
  CONVERSATION: 'CONVERSATION',
  MESSAGE: 'MESSAGE',
  MEDICINE: 'MEDICINE',
  SALE: 'SALE',
  INVENTORY: 'INVENTORY',
  SUPPLIER: 'SUPPLIER',
  STOCK_BATCH: 'STOCK_BATCH',
  CATEGORY: 'CATEGORY',
  SETTINGS: 'SETTINGS',
});

export const ROLE_HIERARCHY = Object.freeze({
  [ROLES.SUPER_ADMIN]: 100,
  [ROLES.ADMIN]: 10,
  [ROLES.MANAGER]: 8,
  [ROLES.PHARMACIST]: 7,
  [ROLES.INVENTORY_MANAGER]: 6,
  [ROLES.CASHIER]: 5,
  [ROLES.AUDITOR]: 1,
  [ROLES.PATIENT]: 0,
});

export const STAFF_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.MANAGER,
  ROLES.PHARMACIST,
  ROLES.CASHIER,
  ROLES.INVENTORY_MANAGER,
  ROLES.AUDITOR,
]);

export const INVITATION_TTL_HOURS = 48;

export const INVITATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
});

export const PROFESSIONAL_VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
});

export const PHARMACY_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED',
});

export const MEMBERSHIP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REMOVED: 'REMOVED',
});

// Granular permissions for RBAC
export const PERMISSIONS = Object.freeze({
  // Medicine
  VIEW_MEDICINES: 'VIEW_MEDICINES',
  CREATE_MEDICINE: 'CREATE_MEDICINE',
  UPDATE_MEDICINE: 'UPDATE_MEDICINE',
  DELETE_MEDICINE: 'DELETE_MEDICINE',
  // Patients
  VIEW_PATIENTS: 'VIEW_PATIENTS',
  // Prescriptions
  VIEW_PRESCRIPTIONS: 'VIEW_PRESCRIPTIONS',
  REVIEW_PRESCRIPTIONS: 'REVIEW_PRESCRIPTIONS',
  APPROVE_PRESCRIPTIONS: 'APPROVE_PRESCRIPTIONS',
  // Chat / Consultation
  CHAT_WITH_PATIENT: 'CHAT_WITH_PATIENT',
  PROVIDE_MEDICATION_ADVICE: 'PROVIDE_MEDICATION_ADVICE',
  // Stock / Inventory
  VIEW_STOCK: 'VIEW_STOCK',
  MANAGE_STOCK: 'MANAGE_STOCK',
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  // Sales
  CREATE_SALE: 'CREATE_SALE',
  VIEW_ORDERS: 'VIEW_ORDERS',
  PROCESS_PAYMENT: 'PROCESS_PAYMENT',
  PRINT_RECEIPT: 'PRINT_RECEIPT',
  // Staff / Admin
  MANAGE_STAFF: 'MANAGE_STAFF',
  INVITE_STAFF: 'INVITE_STAFF',
  REMOVE_STAFF: 'REMOVE_STAFF',
  MANAGE_PHARMACY: 'MANAGE_PHARMACY',
  VIEW_AUDIT: 'VIEW_AUDIT',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',
});

// Roles that require professional verification
export const PROFESSIONAL_ROLES = Object.freeze([
  ROLES.PHARMACIST,
]);

export const NOTIFICATION_TYPES = Object.freeze({
  PRESCRIPTION_SUBMITTED: 'PRESCRIPTION_SUBMITTED',
  PRESCRIPTION_UNDER_REVIEW: 'PRESCRIPTION_UNDER_REVIEW',
  PRESCRIPTION_APPROVED: 'PRESCRIPTION_APPROVED',
  PRESCRIPTION_REJECTED: 'PRESCRIPTION_REJECTED',
  PRESCRIPTION_COMPLETED: 'PRESCRIPTION_COMPLETED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  PHARMACIST_RESPONSE: 'PHARMACIST_RESPONSE',
});
