export const medicineCategories = [
  ['Analgesics', 'Pain and fever relief medicines'],
  ['Antibiotics', 'Prescription antibacterial medicines'],
  ['Antihistamines', 'Allergy symptom relief medicines'],
  ['Gastrointestinal', 'Digestive system medicines'],
  ['Respiratory', 'Medicines used for respiratory conditions'],
  ['Diabetes', 'Medicines used in diabetes care'],
  ['Cardiovascular', 'Medicines used in cardiovascular care'],
  ['Antimalarials', 'Medicines used in malaria treatment'],
  ['Nutrition and Rehydration', 'Supplements and oral rehydration products'],
];

const common = {
  manufacturer: 'Multiple approved manufacturers',
  is_active: true,
  is_controlled: false,
  image_url: null,
  max_stock_level: 500,
};

export const medicineCatalog = [
  { ...common, name: 'Paracetamol 500 mg Tablets', generic_name: 'Paracetamol', brand_name: null, category: 'Analgesics', description: 'Oral analgesic and antipyretic tablet for temporary relief of mild-to-moderate pain and fever.', price: 100, cost_price: 60, requires_prescription: false, strength: '500 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C in a dry place and protect from moisture.', side_effects: 'Usually well tolerated at recommended doses; hypersensitivity reactions may occur rarely.', contraindications: 'Do not use with severe active liver disease or known hypersensitivity. Avoid combining with other paracetamol-containing products.', symptoms: 'pain, fever, headache, body aches', indications: 'Temporary relief of mild-to-moderate pain and fever. Use only according to the approved label or prescriber instructions.', tags: ['pain', 'fever', 'otc', 'analgesic'], min_stock_level: 100, current_stock: 350, reorder_point: 150, barcode: 'URM-PARA-500-TAB' },
  { ...common, name: 'Ibuprofen 200 mg Tablets', generic_name: 'Ibuprofen', brand_name: null, category: 'Analgesics', description: 'Non-steroidal anti-inflammatory medicine for short-term pain, inflammation, and fever relief.', price: 200, cost_price: 120, requires_prescription: false, strength: '200 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C and protect from moisture.', side_effects: 'May cause stomach discomfort, nausea, heartburn, dizziness, or allergic reactions.', contraindications: 'Avoid with active peptic ulcer, severe kidney disease, NSAID allergy, and during the final trimester of pregnancy unless specifically directed.', symptoms: 'pain, inflammation, fever, dental pain', indications: 'Short-term relief of pain, inflammation, and fever according to the approved label.', tags: ['pain', 'inflammation', 'fever', 'nsaid'], min_stock_level: 80, current_stock: 240, reorder_point: 120, barcode: 'URM-IBU-200-TAB' },
  { ...common, name: 'Amoxicillin 500 mg Capsules', generic_name: 'Amoxicillin', brand_name: null, category: 'Antibiotics', description: 'Penicillin-class antibacterial medicine supplied only against a valid prescription.', price: 350, cost_price: 220, requires_prescription: true, strength: '500 mg', dosage_form: 'Capsule', unit_of_measure: 'CAPSULE', storage_conditions: 'Store below 25°C in the original package and protect from moisture.', side_effects: 'Nausea, diarrhea, rash, and allergic reactions may occur.', contraindications: 'Do not use with a history of serious penicillin allergy. Clinical assessment is required before dispensing.', symptoms: 'bacterial infection', indications: 'Treatment of susceptible bacterial infections only when prescribed by an authorized clinician.', tags: ['antibiotic', 'penicillin', 'prescription'], min_stock_level: 80, current_stock: 180, reorder_point: 120, barcode: 'URM-AMOX-500-CAP' },
  { ...common, name: 'Azithromycin 500 mg Tablets', generic_name: 'Azithromycin', brand_name: null, category: 'Antibiotics', description: 'Macrolide antibacterial medicine for clinician-selected susceptible infections.', price: 1200, cost_price: 800, requires_prescription: true, strength: '500 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C in a dry place.', side_effects: 'Nausea, diarrhea, abdominal discomfort, headache, and rarely heart-rhythm effects.', contraindications: 'Do not use with macrolide hypersensitivity. Review interacting medicines and cardiac risk before dispensing.', symptoms: 'bacterial infection', indications: 'Treatment of susceptible bacterial infections according to a valid prescription.', tags: ['antibiotic', 'macrolide', 'prescription'], min_stock_level: 40, current_stock: 90, reorder_point: 60, barcode: 'URM-AZIT-500-TAB' },
  { ...common, name: 'Cetirizine 10 mg Tablets', generic_name: 'Cetirizine hydrochloride', brand_name: null, category: 'Antihistamines', description: 'Second-generation antihistamine used for temporary allergy symptom relief.', price: 250, cost_price: 140, requires_prescription: false, strength: '10 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C and protect from moisture.', side_effects: 'Sleepiness, dry mouth, fatigue, or headache may occur.', contraindications: 'Do not use with known hypersensitivity. Seek advice for significant kidney impairment or when taking sedating medicines.', symptoms: 'allergy, sneezing, itching, runny nose, hives', indications: 'Temporary relief of allergic rhinitis and urticaria symptoms according to the label.', tags: ['allergy', 'antihistamine', 'otc'], min_stock_level: 60, current_stock: 160, reorder_point: 90, barcode: 'URM-CET-10-TAB' },
  { ...common, name: 'Omeprazole 20 mg Capsules', generic_name: 'Omeprazole', brand_name: null, category: 'Gastrointestinal', description: 'Proton-pump inhibitor that reduces gastric acid production.', price: 400, cost_price: 250, requires_prescription: false, strength: '20 mg', dosage_form: 'Delayed-release capsule', unit_of_measure: 'CAPSULE', storage_conditions: 'Store below 25°C in a dry place and keep container closed.', side_effects: 'Headache, abdominal discomfort, nausea, constipation, or diarrhea may occur.', contraindications: 'Do not use with known hypersensitivity. Persistent or alarm symptoms require clinical assessment.', symptoms: 'heartburn, acid reflux, indigestion', indications: 'Short-term acid-related symptom management according to the approved label; longer treatment requires clinical review.', tags: ['reflux', 'heartburn', 'ppi'], min_stock_level: 60, current_stock: 140, reorder_point: 90, barcode: 'URM-OME-20-CAP' },
  { ...common, name: 'Salbutamol 100 mcg Inhaler', generic_name: 'Salbutamol', brand_name: null, category: 'Respiratory', description: 'Short-acting bronchodilator inhaler for relief of reversible airway narrowing.', price: 6500, cost_price: 4800, requires_prescription: true, strength: '100 mcg per actuation', dosage_form: 'Metered-dose inhaler', unit_of_measure: 'INHALER', storage_conditions: 'Store below 30°C. Protect from direct sunlight, heat, freezing, and puncture.', side_effects: 'Tremor, fast heartbeat, palpitations, headache, or muscle cramps may occur.', contraindications: 'Do not use with known hypersensitivity. Frequent need or poor response requires urgent clinical review.', symptoms: 'wheezing, shortness of breath, bronchospasm', indications: 'Relief of reversible bronchospasm according to an individualized treatment plan.', tags: ['asthma', 'inhaler', 'bronchodilator', 'prescription'], min_stock_level: 20, current_stock: 55, reorder_point: 30, barcode: 'URM-SALB-100-INH' },
  { ...common, name: 'Metformin 500 mg Tablets', generic_name: 'Metformin hydrochloride', brand_name: null, category: 'Diabetes', description: 'Oral blood-glucose-lowering medicine used as part of clinician-managed type 2 diabetes care.', price: 300, cost_price: 180, requires_prescription: true, strength: '500 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C and protect from moisture.', side_effects: 'Nausea, diarrhea, abdominal discomfort, reduced appetite, and vitamin B12 reduction with long-term use may occur.', contraindications: 'Contraindicated in severe kidney impairment and metabolic acidosis. Kidney function and clinical suitability must be assessed.', symptoms: 'high blood glucose, type 2 diabetes', indications: 'Management of type 2 diabetes as prescribed alongside diet and lifestyle measures.', tags: ['diabetes', 'blood glucose', 'prescription'], min_stock_level: 100, current_stock: 300, reorder_point: 150, barcode: 'URM-MET-500-TAB' },
  { ...common, name: 'Amlodipine 5 mg Tablets', generic_name: 'Amlodipine', brand_name: null, category: 'Cardiovascular', description: 'Calcium-channel blocker used in clinician-managed blood-pressure and angina treatment.', price: 300, cost_price: 180, requires_prescription: true, strength: '5 mg', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C in the original package.', side_effects: 'Ankle swelling, flushing, headache, dizziness, fatigue, or palpitations may occur.', contraindications: 'Do not use with known hypersensitivity. Blood pressure and clinical suitability require assessment.', symptoms: 'high blood pressure, angina', indications: 'Management of hypertension or angina according to a valid prescription.', tags: ['hypertension', 'blood pressure', 'prescription'], min_stock_level: 80, current_stock: 220, reorder_point: 120, barcode: 'URM-AMLO-5-TAB' },
  { ...common, name: 'Artemether/Lumefantrine 20/120 mg Tablets', generic_name: 'Artemether and lumefantrine', brand_name: null, category: 'Antimalarials', description: 'Fixed-dose antimalarial combination for confirmed uncomplicated malaria under clinical guidance.', price: 3500, cost_price: 2500, requires_prescription: true, strength: '20 mg/120 mg', dosage_form: 'Tablet', unit_of_measure: 'TREATMENT_PACK', storage_conditions: 'Store below 30°C and protect from moisture.', side_effects: 'Headache, dizziness, reduced appetite, nausea, abdominal pain, or palpitations may occur.', contraindications: 'Not for severe malaria. Review cardiac risk, pregnancy status, age, weight, and interacting medicines before supply.', symptoms: 'confirmed uncomplicated malaria', indications: 'Treatment of confirmed uncomplicated malaria using the correct weight-based treatment pack under clinical guidance.', tags: ['malaria', 'antimalarial', 'prescription'], min_stock_level: 30, current_stock: 75, reorder_point: 45, barcode: 'URM-AL-20-120' },
  { ...common, name: 'Oral Rehydration Salts Sachet', generic_name: 'Glucose-electrolyte oral rehydration salts', brand_name: null, category: 'Nutrition and Rehydration', description: 'Powder sachet for preparation of oral rehydration solution according to package directions.', price: 500, cost_price: 300, requires_prescription: false, strength: 'One sachet for stated water volume', dosage_form: 'Powder for oral solution', unit_of_measure: 'SACHET', storage_conditions: 'Store sachets below 30°C in a dry place. Use prepared solution within the label-specified period.', side_effects: 'Incorrect dilution may cause electrolyte imbalance; vomiting may occur with rapid administration.', contraindications: 'Severe dehydration, inability to drink, persistent vomiting, blood in stool, or altered consciousness requires urgent medical care.', symptoms: 'diarrhea, dehydration, fluid loss', indications: 'Prevention and treatment of mild-to-moderate dehydration from diarrhea when prepared exactly as labeled.', tags: ['rehydration', 'diarrhea', 'ors', 'otc'], min_stock_level: 100, current_stock: 400, reorder_point: 150, barcode: 'URM-ORS-SACHET' },
  { ...common, name: 'Ferrous Sulfate/Folic Acid Tablets', generic_name: 'Ferrous sulfate and folic acid', brand_name: null, category: 'Nutrition and Rehydration', description: 'Iron and folic-acid combination used for prevention or treatment of deficiency when clinically appropriate.', price: 200, cost_price: 120, requires_prescription: false, strength: 'Refer to pack strength', dosage_form: 'Tablet', unit_of_measure: 'TABLET', storage_conditions: 'Store below 25°C, protect from moisture, and keep out of reach of children.', side_effects: 'Nausea, abdominal discomfort, constipation, diarrhea, and dark stools may occur.', contraindications: 'Do not use for iron-overload disorders or anemia not caused by iron deficiency without clinical assessment.', symptoms: 'iron deficiency, nutritional supplementation', indications: 'Prevention or treatment of iron and folate deficiency according to clinical advice and the approved label.', tags: ['iron', 'folic acid', 'supplement'], min_stock_level: 100, current_stock: 280, reorder_point: 150, barcode: 'URM-FEFA-TAB' },
];
